[package]
name = "training_platform"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.1.0"
bollard = "0.13.0"
serde = { version = "1.0.138", features = ["derive"] }
serde_json = "1.0.82"
tokio = { version = "1.20.1", features = ["full"] }