version: '3'

services:
  # CTFd -->
  ctfd:
    extends:
      file: CTFd-3.5.0/docker-compose.yml
      service: ctfd

  nginx:
    extends:
      file: CTFd-3.5.0/docker-compose.yml
      service: nginx
    ports:
      - 443:443
    volumes:
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro

  db:
    extends:
      file: CTFd-3.5.0/docker-compose.yml
      service: db

  cache:
    extends:
      file: CTFd-3.5.0/docker-compose.yml
      service: cache

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  # <-- CTFd

  rust-server:
    build:
      context: ./rust-server/
    networks:
      training_platform:
        ipv4_address: 10.10.10.2

  # VPN
  wireguard:
    image: linuxserver/wireguard
    environment:
      - TZ=US/Boston
      # - SERVERURL=example.org
      - PEERS=1
      - ALLOWEDIPS=10.10.10.2
      - /path/to/appdata/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

networks:
  training_platform:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
  # CTFd
  default:
  internal:
    internal: true
