version: '3'

services:
  ctfd:
    build:
      context: ./CTFd-3.5.0/
    depends_on:
      - rust-server
    networks:
      - training_platform

  rust-server:
    build:
      context: ./rust-server/
    networks:
      - training_platform

networks:
  training_platform:
    driver: bridge
