version: '3'

services:
  # CTFd -->
  ctfd:
    extends:
      file: CTFd-3.5.0/docker-compose.yml
      service: ctfd
    environment:
      VIRTUAL_HOST=test.training.umasscybersec.org
      VIRTUAL_PORT=8000
      LETSENCRYPT_HOST=test.training.umasscybersec.org
      LETSENCRYPT_EMAIL=umasscybersec@gmail.com

  nginx:
    extends:
      file: CTFd-3.5.0/docker-compose.yml
      service: nginx
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 443:443

  db:
    extends:
      file: CTFd-3.5.0/docker-compose.yml
      service: db

  cache:
    extends:
      file: CTFd-3.5.0/docker-compose.yml
      service: cache

  # For https
  acme-companion:
    image: nginxproxy/acme-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    volumes_from:
      - nginx
    environment:
      DEFAULT_EMAIL=umasscybersec@gmail.com

  # <-- CTFd

  rust-server:
    build:
      context: ./rust-server/
    networks:
      training_platform:
        ipv4_address: 10.10.10.2

networks:
  training_platform:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
  # CTFd
  default:
  internal:
    internal: true
