version: '3'

services:
  ctfd:
    extends:
      file: CTFd-3.5.0/docker-compose.yml

  rust-server:
    build:
      context: ./rust-server/
    networks:
      training_platform:
        ipv4_address: 10.10.10.2

networks:
  training_platform:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
